name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - flake8
  - git
  - intake
  - intake-xarray
  - ipykernel
  - isort
  - make
  - nbsphinx
  - numpydoc
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.7
  - pyyaml
  - recommonmark
  - sphinx_rtd_theme
  - sphinx>=1.6
  - tqdm
  - xarray
  - docrep
  - s3fs
  - fsspec
