name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - git
  - intake-xarray>=0.3.1
  - xarray=>0.13
  - ipykernel
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - python=3.6
  - pyyaml
  - tqdm
  - s3fs
  - gcsfs
  - fsspec
