name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - flake8
  - git
  - intake-xarray>=0.3.1
  - ipykernel
  - isort
  - make
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.7
  - pyyaml
  - tqdm
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/intake/filesystem_spec.git#egg=fsspec
    - git+https://github.com/dask/gcsfs.git
    - git+https://github.com/dask/s3fs.git
