name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dask>=2.2
  - git
  - intake
  - intake-xarray
  - ipykernel
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.6
  - pyyaml
  - tqdm
  - xarray
  - docrep
  - s3fs
  - fsspec
