name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - flake8
  - git
  - intake-xarray>=0.3.1
  - xarray=>0.13
  - ipykernel
  - isort
  - make
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - python=3.8
  - s3fs
  - gcsfs
  - fsspec
