name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - coverage
  - dask
  - distributed
  - flake8
  - intake
  - intake-xarray
  - ipykernel
  - isort
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pandoc
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.7
  - pytoml
  - pyyaml
  - recommonmark
  - sphinx_rtd_theme
  - sphinx>=1.6
  - tqdm
  - xarray
  - pip=18.1
  - make
  - pip:
    - sphinx_copybutton
