name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - intake-xarray>=0.3.1
  - xarray=>0.13
  - nbsphinx
  - python=3.7
  - pyyaml
  - sphinx_rtd_theme
  - dask
  - tqdm
  - git
  - make
  - jupyter_client
  - s3fs
  - fsspec
  - watermark
