name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - dask
  - intake
  - intake-xarray
  - nbsphinx
  - numpydoc
  - python=3.7
  - pyyaml
  - sphinx_rtd_theme
  - tqdm
  - xarray
  - docrep
  - click
